use std::path::PathBuf;
use std::process::Command;

use anyhow::{Result, bail};
use capy_clips_align::{AlignOptions, align};
use capy_clips_core::{
    CutReport, PreviewClip, PreviewTimelines, Sentences, remap_words_to_clip_ms,
};
use capy_clips_cut::{CutOptions, cut_plan};
use capy_clips_download::{DownloadOptions, download};
use capy_clips_transcribe::{TranscribeOptions, transcribe};
use clap::{Args, Subcommand};
use serde_json::{Value, json};

#[derive(Debug, Args)]
pub struct ClipsArgs {
    #[command(subcommand)]
    command: ClipsCommand,
}

#[derive(Debug, Subcommand)]
enum ClipsCommand {
    Doctor,
    Download(DownloadArgs),
    Transcribe(TranscribeArgs),
    Align(AlignArgs),
    Cut(CutArgs),
    Preview(PreviewArgs),
}

#[derive(Debug, Args)]
struct DownloadArgs {
    #[arg(long)]
    url: String,
    #[arg(long)]
    out_dir: PathBuf,
    #[arg(long, default_value_t = 1080)]
    format_height: u16,
}

#[derive(Debug, Args)]
struct TranscribeArgs {
    #[arg(long)]
    video: PathBuf,
    #[arg(long)]
    out_dir: PathBuf,
    #[arg(long, default_value = "large-v3")]
    model: String,
    #[arg(long, default_value = "en")]
    language: String,
    #[arg(long, default_value_t = 1)]
    jobs: usize,
}

#[derive(Debug, Args)]
struct AlignArgs {
    #[arg(long)]
    video: PathBuf,
    #[arg(long)]
    srt_path: PathBuf,
    #[arg(long)]
    out_dir: PathBuf,
    #[arg(long, default_value = "auto")]
    language: String,
}

#[derive(Debug, Args)]
struct CutArgs {
    #[arg(long)]
    video: PathBuf,
    #[arg(long)]
    sentences_path: PathBuf,
    #[arg(long)]
    plan_path: PathBuf,
    #[arg(long)]
    out_dir: PathBuf,
    #[arg(long, default_value_t = 0.0)]
    margin_sec: f64,
}

#[derive(Debug, Args)]
struct PreviewArgs {
    #[arg(long)]
    sentences_path: PathBuf,
    #[arg(long)]
    cut_report_path: PathBuf,
    #[arg(long)]
    out_path: PathBuf,
    #[arg(long, default_value = "Capybara Clips Preview")]
    title: String,
    #[arg(long, default_value = "Generated by capy clips preview")]
    subtitle: String,
    #[arg(long, default_value = "#2563eb")]
    accent: String,
    #[arg(long, default_value = "capybara")]
    theme: String,
}

pub fn handle(args: ClipsArgs) -> Result<(), String> {
    run(args).map_err(|error| format!("{error:#}"))
}

fn run(args: ClipsArgs) -> Result<()> {
    match args.command {
        ClipsCommand::Doctor => doctor(),
        ClipsCommand::Download(args) => download_command(args),
        ClipsCommand::Transcribe(args) => transcribe_command(args),
        ClipsCommand::Align(args) => align_command(args),
        ClipsCommand::Cut(args) => cut_command(args),
        ClipsCommand::Preview(args) => preview_command(args),
    }
}

fn doctor() -> Result<()> {
    print_value(json!({
        "ok": command_available("yt-dlp", &["--version"])
            && command_available("ffmpeg", &["-version"])
            && command_available("ffprobe", &["-version"]),
        "tools": {
            "yt-dlp": tool_status("yt-dlp", &["--version"]),
            "ffmpeg": tool_status("ffmpeg", &["-version"]),
            "ffprobe": tool_status("ffprobe", &["-version"]),
            "python": tool_status(path_or_env("CAPY_CLIPS_PYTHON_BIN", "/Users/Zhuanz/.venvs/align/bin/python3").as_str(), &["--version"]),
        },
        "helpers": {
            "whisper_script": env_or_default("CAPY_CLIPS_WHISPER_SCRIPT", "scripts/transcribe_whisper_timestamped.py"),
            "align_script": env_or_default("CAPY_CLIPS_ALIGN_SCRIPT", "scripts/align_whisperx.py"),
        },
        "commands": ["download", "transcribe", "align", "cut", "preview"],
    }))
}

fn download_command(args: DownloadArgs) -> Result<()> {
    let summary = download(&DownloadOptions {
        url: args.url,
        out_dir: args.out_dir,
        format_height: args.format_height,
    })?;

    print_value(json!({
        "video_path": summary.video_path,
        "metadata_path": summary.metadata_path,
        "metadata": summary.metadata,
    }))
}

fn transcribe_command(args: TranscribeArgs) -> Result<()> {
    let summary = transcribe(&TranscribeOptions {
        video: args.video,
        out_dir: args.out_dir,
        model: args.model,
        language: args.language,
        jobs: args.jobs,
    })?;

    print_value(json!({
        "audio_path": summary.audio_path,
        "audio_duration_sec": summary.audio_duration_sec,
        "total_words": summary.total_words,
        "total_sentences": summary.total_sentences,
    }))
}

fn align_command(args: AlignArgs) -> Result<()> {
    let summary = align(&AlignOptions {
        video: args.video,
        srt_path: args.srt_path,
        out_dir: args.out_dir,
        language: args.language,
    })?;

    print_value(json!({
        "audio_path": summary.audio_path,
        "audio_duration_sec": summary.audio_duration_sec,
        "language": summary.language,
        "total_words": summary.total_words,
        "total_sentences": summary.total_sentences,
    }))
}

fn cut_command(args: CutArgs) -> Result<()> {
    let report_path = args.out_dir.join("cut_report.json");
    let report = cut_plan(
        &CutOptions {
            video: args.video,
            sentences_path: args.sentences_path,
            plan_path: args.plan_path,
            out_dir: args.out_dir,
            margin_sec: args.margin_sec,
        },
        |event| {
            if let Ok(line) = serde_json::to_string(event) {
                println!("{line}");
            }
        },
    )?;

    report.write_to_path(&report_path)?;
    eprintln!(
        "cut complete: {} succeeded, {} failed",
        report.success.len(),
        report.failed.len()
    );
    if !report.failed.is_empty() {
        bail!("cut failed for {} clip(s)", report.failed.len());
    }
    Ok(())
}

fn preview_command(args: PreviewArgs) -> Result<()> {
    let sentences = Sentences::from_path(&args.sentences_path)?;
    let report = CutReport::from_path(&args.cut_report_path)?;
    let clips = report
        .success
        .iter()
        .map(|clip| {
            Ok(PreviewClip {
                clip_num: clip.clip_num,
                title: clip.title.clone(),
                file: clip.file.clone(),
                start_sec: clip.start,
                end_sec: clip.end,
                duration_sec: clip.duration,
                from_id: clip.from_id,
                to_id: clip.to_id,
                words: remap_words_to_clip_ms(
                    &sentences,
                    clip.from_id,
                    clip.to_id,
                    clip.start,
                    clip.duration,
                )?,
            })
        })
        .collect::<Result<Vec<_>>>()?;

    let timelines = PreviewTimelines {
        version: "1".to_string(),
        title: args.title,
        subtitle: args.subtitle,
        accent: args.accent,
        theme: args.theme,
        clips,
    };
    timelines.write_to_path(&args.out_path)?;

    print_value(json!({
        "out_path": args.out_path,
        "clips": timelines.clips.len(),
    }))
}

fn print_value(value: Value) -> Result<()> {
    crate::print_json(&value).map_err(anyhow::Error::msg)
}

fn tool_status(tool: &str, version_args: &[&str]) -> Value {
    match Command::new(tool).args(version_args).output() {
        Ok(output) => json!({
            "available": output.status.success(),
            "exit_code": output.status.code(),
        }),
        Err(error) => json!({
            "available": false,
            "error": error.to_string(),
        }),
    }
}

fn command_available(tool: &str, version_args: &[&str]) -> bool {
    Command::new(tool)
        .args(version_args)
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

fn env_or_default(key: &str, default: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| default.to_string())
}

fn path_or_env(key: &str, default: &str) -> String {
    env_or_default(key, default)
}
